# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 995b214ca414191e28ab46e3f93ffa5010efafbc0d93e0865ea29dd778f0e0b9b44bb5da9446df85dd0fbd63822da4825a194d29fab243de7e2a661f4cbb2ad7

test:
  secret_key_base: 5ea2e8d2f4796f84cbe65c8abb8eeaa8e992b1eb54fb1f6420d487e9403c1924cbd12ad3cdaab0819dc8891198f7bcbbd46e3d1cc42ab3af5101684645fef690

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
